### ISSUE TITLE
fail to download the weight 

### ISSUE THREAD

**Issue by 1377534928** [ssssshwan/TLDR#2]
Thanks for your good work! I can not download the weight file using bash command from script. Can you share the link or other ways to download?Thank you very much!

**Comment by ssssshwan** [comment]
Thank you for reaching out! Can you tell me what causes it to fail? 
It works fine for me, so if the link is wrong, I'll try to recreate it.

**Comment by 1377534928** [comment]
> Thank you for reaching out! Can you tell me what causes it to fail? It works fine for me, so if the link is wrong, I'll try to recreate it.
Sorry, It is my fault. I have successfully download it. May you tell me how much is the img_scale when you evaluate the mapillary dataset using your provided config file. I meet " cuda out of memory" when i test it using gpu (24GB).

**Comment by whyandbecause** [comment]
Hi，thanks for you interesting work! I'm trying to get the inference results, but I can't download the pre-trained weight with provided script, because my server can't connect to google directly, I need access google with another computer without python environment. So, can you share a link for weight files with google driver? or, can you share the inference results (Trained on G, tested on C,B,M)? Thanks a lot!

**Comment by ssssshwan** [comment]
Hi,
Thanks for reaching out.
This is the link to the pre-trained weight!
https://drive.google.com/file/d/1YsD9tLCdJG0QlcdNWNVhlMRjC69L54Gq/view?usp=sharing

**Comment by whyandbecause** [comment]
Thanks for sharing, it helped me a lot！
